### ISSUE TITLE
Node error executing mtemplate on OS X

### ISSUE THREAD

**Issue by jsartelle** [VisualSolutions/mtemplate#1]
Attempting to run mtemplate on OS X (and possibly other platforms) gives this error: "env: node\r: No such file or directory"

This is due to mtemplate using DOS style line breaks. Converting all the files to use UNIX style line breaks fixes the issue. See here: http://stackoverflow.com/questions/18492897/env-node-r-no-such-file-or-directory-with-cordova-cli

**Comment by eviefp** [comment]
Hopefully the gitattributes commit https://github.com/VisualSolutions/mtemplate/commit/e281d31daf332a5711fdb17f0f717860fefd2b86 will fix this

Will ask you to check when I publish the update
